#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : setuptools_scm_git_archive
Version  : 1.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/18/00/754438f629dfff1ecdbb31c8c23effe8bcfdbf65dbaf1cbed58eab286d82/setuptools_scm_git_archive-1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/18/00/754438f629dfff1ecdbb31c8c23effe8bcfdbf65dbaf1cbed58eab286d82/setuptools_scm_git_archive-1.0.tar.gz
Summary  : setuptools_scm plugin for git archives
Group    : Development/Tools
License  : MIT
Requires: setuptools_scm_git_archive-python3
Requires: setuptools_scm_git_archive-python
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : setuptools_scm

%description
that adds support for git archives (for example the ones GitHub automatically
        generates).
        
        Note that it only works for archives of tagged commits (because git currently
        lacks a format option equivalent to ``git describe --tags``).
        
        Usage
        -----
        
        Add ``'setuptools_scm_git_archive'`` to the ``setup_requires`` parameter in your

%package python
Summary: python components for the setuptools_scm_git_archive package.
Group: Default
Requires: setuptools_scm_git_archive-python3

%description python
python components for the setuptools_scm_git_archive package.


%package python3
Summary: python3 components for the setuptools_scm_git_archive package.
Group: Default
Requires: python3-core

%description python3
python3 components for the setuptools_scm_git_archive package.


%prep
%setup -q -n setuptools_scm_git_archive-1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525896641
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
